name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Windows app
        run: npm run make
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: |
            out/make/squirrel.windows/x64/*.exe
            out/make/zip/win32/x64/*.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Debug - List directories before build
        run: |
          ls -la
          mkdir -p out/Toolbox-darwin-arm64/
      - name: Build macOS app
        run: npm run package
      - name: Debug - Check output directories
        run: |
          ls -la out/
          find . -name "*.app" -type d
      - name: Create ZIP for macOS
        run: |
          cd out
          zip -r Toolbox-mac.zip .
          cd ..
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            out/Toolbox-mac.zip
            out/**/*.zip
            out/**/*.dmg

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-app
          path: windows-app
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-app
          path: macos-app
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            windows-app/**/*
            macos-app/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 